### ISSUE TITLE
inkplate10 latest version enclosure

### ISSUE THREAD

**Issue by dcolens** [e-radionicacom/Inkplate-10-hardware#4]
the version of inkplate 10 I received does not have touchpads like described on this repo, could you share the enclosure STLs for this version too?

**Comment by rsoric** [comment]
Hi @dcolens , just noted that the repository hasn't been updated yet but here's the files you need for the new version


[inkplate10_case_stl_files.zip](https://github.com/SolderedElectronics/Inkplate-10-hardware/files/12683693/inkplate10_case_stl_files.zip)

**Comment by dcolens** [comment]
Thanks for the prompt reply :-)
