### ISSUE TITLE
Inkplate 10 3D model.step is not a valid file

### ISSUE THREAD

**Issue by clivebagley** [e-radionicacom/Inkplate-10-hardware#5]
Import to Creo (9) or Solidworks (2022) fail with invalid file

--EDIT-- 

My bad, I had managed to save the HTML - DUH!

**Comment by clivebagley** [comment]
![SW](https://github.com/SolderedElectronics/Inkplate-10-hardware/assets/26936415/e9d97161-a7ac-419c-ad94-d2c29130471f)
![creo](https://github.com/SolderedElectronics/Inkplate-10-hardware/assets/26936415/391dd49b-c138-4ba6-971d-d9d4cb7d95ab)

**Comment by rsoric** [comment]
Hi @clivebagley 

Glad you got it sorted :)
